### ISSUE TITLE
Flutter not printing colors

### ISSUE THREAD

**Issue by dash-dash-force** [magillus/flutter-fimber#72] opened 2020-03-27 13:26 UTC
Hi guys,

I'm using Fimber for a project, and wanted to have colored output. I used the code below. However, I still get white-only output. I'm using iTerm2 on MacOS Catelina (10.15.3). 

```dart
final tree = DebugTree(useColors: true);
Fimber.plantTree(tree);
```

Any idea?

**Comment by magillus** [comment] 2020-03-31 23:59
Hi, thank you for filing issue.
@dash-dash-force Do you have any unexpected characters?
Does other terminal (original MacOS) displays colors?

Regards,
Mateusz

**Comment by dash-dash-force** [comment] 2020-04-02 07:42
Hey @magillus, thanks for your response. Both do not display colors as output of the app. I do see unexpected characters however, e.g. this output:

flutter: \^[[32m2020-04-02T09:39:55.414506

The \^[[32m wasn't there normally.

N

**Comment by magillus** [comment] 2020-04-02 16:05
hmm.. thanks, it seems like the terminal app doesn't support this or the text encoding isn't picked up/setup.
I will try to investigate this, I have access to Mac to try this out.

**Comment by dash-dash-force** [comment] 2020-04-03 07:19
Awesome @magillus! Hope you'll find something :).

**Comment by magillus** [comment] 2020-04-07 14:34
I can't reproduce it:
![image](https://user-images.githubusercontent.com/729803/78681903-ef265500-78b2-11ea-82ba-a6fef419385d.png)

Left is iTerm on right is MacOs terminal - both render colors correctly.

**Comment by dash-dash-force** [comment] 2020-04-07 19:22
@magillus too bad, but thanks a lot for checking! 
Last question: which MacOS version were you on?

**Comment by magillus** [comment] 2020-04-08 13:14
I don't remember from top of my head - will check later.
git clone repo and run this test yourself: `dart test/colorize_test.dart`

**Comment by dash-dash-force** [comment] 2020-04-08 16:25
@magillus it works there! Weird .... 🤔

**Comment by magillus** [comment] 2020-04-09 02:02
If you could create sample CLI app and try it again. But not sure what would be different then the test.

**Comment by magillus** [comment] 2020-05-05 12:25
Closing the issue, if you still run into this on CLI in terminal please submit reproducible example and reopen issue.

Thank you.

**Closed by magillus** 2020-05-05 12:25 UTC
